logging:
  level:
    root: INFO
    com.anhnt.configuration: WARN
server:
  port: 8020
  servlet:
    contextPath: /configuration


spring:
  application:
    name: configuration
  profiles:
    active:
      - jdbc
      - vault
  cloud:
    config:
      server:
        encrypt:
          enabled: true
        jdbc:
          sql: SELECT `key`, value from  properties where (application=? or application='default') and profile=? and label=?
          order: 1
        vault:
          host: localhost
          port: 8200
          scheme: http
          backend: secret
#          defaultKey: myapp
#          profileSeparator: ,
          kvVersion: 2
          skipSslValidation: true
          timeout: 5
          authentication: TOKEN
          token: token_id
        bootstrap: true
        prefix: /config
  datasource:
    url: jdbc:mysql://localhost:3306/configuration?useUnicode=yes&characterEncoding=UTF-8&rewriteBatchedStatements=true&useSSL=false&requireSSL=false
    username: root
    password: Welcome1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false

  security:
    user:
      password: 123
management:
  endpoints:
    web:
      exposure:
        include: "*"
encrypt:
  key: secretkey



#server.context-path=/centralize-configuration
#endpoints.enabled=false
#endpoints.info.enabled=false
#endpoints.health.enabled=false
#api.version=2.1

#server.ssl.enabled=false
#server.ssl.key-store=/data/projects/centralize-configuration/config/equator-keystore.jks
#server.ssl.key-store-password=4s9aHujx9KvPpKKCSe7


# Datasource



# Hikari CP
#spring.datasource.hikari.auto-commit=true
#spring.datasource.hikari.connection-test-query=SELECT 1
#spring.datasource.hikari.connection-timeout=10000
#spring.datasource.hikari.data-source-properties.cachePrepStmts=true
#spring.datasource.hikari.data-source-properties.prepStmtCacheSize=256
#spring.datasource.hikari.data-source-properties.prepStmtCacheSqlLimit=2048
#spring.datasource.hikari.idle-timeout=60000
#spring.datasource.hikari.leak-detection-threshold=60000
#spring.datasource.hikari.max-lifetime=1800000
#spring.datasource.hikari.maximum-pool-size=50
#spring.datasource.hikari.minimum-idle=5
#spring.datasource.hikari.pool-name=equator-centralize-configuration-pool
#spring.datasource.hikari.read-only=false

# JPA


# Date format
#spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss'Z'

# Zipkin
# spring.zipkin.base-url=https://#ZIPKIN_HOST#
#spring.zipkin.enabled=false

#setting for Address format APIs
#spring.servlet.multipart.max-file-size=5MB
#spring.servlet.multipart.max-request-size=5MB

#logging.level.org.apache.http=DEBUG
