logging:
  level:
    root: INFO
    com.anhnt.configuration: WARN
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
    org.springframework.vault: DEBUG
    org.apache.http: DEBUG
server:
  port: 7000
  servlet:
    contextPath: /configuration
spring:
  application:
    name: configuration
  profiles:
    active:
      - jdbc
      - vault
  cloud:
    config:
      server:
        encrypt:
          enabled: true
        jdbc:
          sql: SELECT `key`, value from  properties where (application=? or application='default') and profile=? and label=?
          order: 1
        vault:
          host: localhost
          port: 8200
          scheme: http
          backend: secret/microservice
          kvVersion: 2
          skipSslValidation: true
          timeout: 5
          authentication: TOKEN
          token: token_id
        bootstrap: true
        prefix: /config
  datasource:
    url: jdbc:mysql://localhost:3306/configuration?useUnicode=yes&characterEncoding=UTF-8&rewriteBatchedStatements=true&useSSL=false&requireSSL=false
    username: root
    password: Welcome1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
  security:
    user:
      name: ANHNT
      password: ANHNT-PASS
management:
  endpoints:
    web:
      exposure:
        include: "*"
encrypt:
#  key: customer-secret // Symmetric
  keyStore:   # Asymmetric
    location: classpath:/config-server.jks
    password: my-s70r3-s3cr3t
    alias: config-server-key
    secret: my-k34-s3cr3t
